In [1]:
import pandas as pd
from numpy import array
#import dailyData
datadf = pd.read_csv("dailyData/dailyData.csv") 
#create a column and concatenate all 3 numbers
df = datadf['First Number']

In [2]:
import numpy 
raw_seq = numpy.asarray(df)

In [3]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [4]:
n_steps =3
X, y = split_sequence(raw_seq, n_steps)
y

array([2, 4, 3, 4, 5, 1, 1, 9, 3, 7, 9, 6, 6, 8, 0, 8, 1, 6, 4, 4, 0, 2,
       0, 1, 6, 8, 7, 3, 5, 5, 9, 9, 3, 8, 8, 5, 5, 3, 1, 1, 2, 2, 1, 6,
       8, 8, 5, 6, 4, 5, 9, 1, 8, 3, 9, 4, 7, 7, 6, 3, 0, 2, 2, 2, 0, 1,
       7, 1, 3, 9, 0, 5, 7, 3, 7, 5, 6, 1, 0, 0, 4, 4, 7, 4, 4, 2, 1, 5,
       6, 8, 4, 1, 5, 3, 4, 0, 4, 6, 8, 8, 0, 6, 4, 9, 4, 7, 7, 1, 9, 6,
       7, 4, 5, 9, 5, 2, 0, 9, 1, 0, 4, 1, 3, 5, 0, 4, 1, 3, 0, 3, 8, 3,
       1, 6, 2, 7, 7, 3, 1, 7, 7, 6, 2, 0, 2, 1, 7, 6, 5, 0, 1, 2, 7, 1,
       9, 3, 0, 3, 8, 5, 6, 2, 3, 8, 8, 8, 3, 6, 9, 9, 5, 9, 2, 8, 1, 0,
       0, 0, 1, 5, 1, 5, 2, 6, 2, 4, 7, 8, 6, 4, 6, 8, 9, 0, 5, 7, 9, 9,
       0, 9, 3, 0, 4, 1, 4, 3, 0, 2, 8, 0, 6, 1, 5, 4, 7], dtype=int64)

In [5]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [6]:
predictions = model.predict(X)
print(f"True output: {y[0]}")
print(f"Predicted output: {predictions[0]}")
print(f"Prediction Error: {predictions[0]-y[0]}")

True output: 2
Predicted output: 4.327013134428669
Prediction Error: 2.327013134428669

In [7]:
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [0.00514942 0.14155261 0.07459478]
y-axis intercept:  3.3313594949427205

In [8]:
pd.DataFrame({"Predicted": predictions, "Actual": y, "Error": predictions - y})[["Predicted", "Actual", "Error"]]

     Predicted  Actual     Error
0     4.327013       2  2.327013
1     4.764821       4  0.764821
2     3.959189       3  0.959189
3     4.131653       4  0.131653
4     4.074994       5 -0.925006
5     4.285992       1  3.285992
6     4.134315       1  3.134315
7     3.573254       9 -5.426746
8     4.149415       3  1.149415
9     4.834267       7 -2.165733
10    4.324526       9 -4.675474
11    5.009029       6 -0.990971
12    5.088948       6 -0.911052
13    4.674589       8 -3.325411
14    4.808330       0  4.808330
15    4.494677       8 -3.505323
16    3.969313       1  2.969313
17    4.538375       6 -1.461625
18    3.961676       4 -0.038324
19    4.484204       4  0.484204
20    4.226846       0  4.226846
21    3.918168       2  1.918168
22    3.501147       0  3.501147
23    3.614465       1  2.614465
24    3.416253       6 -2.583747
25    3.920481       8 -4.079519
26    4.782583       7 -2.217417
27    5.016840       3  2.016840
28    4.587207       5 -0.412793
29    4.165037       5 -0.834963
..         ...     ...       ...
185   4.340164       4  0.340164
186   3.943740       7 -3.056260
187   4.430032       8 -3.569968
188   4.939584       6 -1.060416
189   4.947395       4  0.947395
190   4.520250       6 -1.479750
191   4.376035       8 -3.623965
192   4.798031       9 -4.201969
193   5.166030       0  5.166030
194   4.646528       5 -0.353472
195   3.750678       7 -3.249322
196   4.561286       9 -4.438714
197   5.019328       9 -3.980672
198   5.312732       0  5.312732
199   4.651678       9 -4.348322
200   4.049057       3  1.049057
201   4.829117       0  4.829117
202   3.802362       4 -0.197638
203   3.645187       1  2.645187
204   3.972165       4 -0.027835
205   3.791889       3  0.791889
206   4.126504       0  4.126504
207   3.776615       2  1.776615
208   3.495997       8 -4.504003
209   4.211223       0  4.211223
210   4.474079       6 -1.525921
211   3.820124       1  2.820124
212   4.255270       5 -0.744730
213   3.876783       4 -0.123217
214   4.342651       7 -2.657349

[215 rows x 3 columns]

In [9]:
x_min = X.min()
x_max = X.max()
y_min_actual = y.min()
y_max_actual = y.max()

In [10]:
y_min = model.coef_ + model.intercept_ * x_min
y_max = model.coef_  + model.intercept_ * x_max
print(f"Actual Min Value: {y_min_actual}")
print(f"Calculated Min Value: {y_min}")
print(f"Actual Max Value: {y_max_actual}")
print(f"Calculated Max Value: {y_max}")

Actual Min Value: 0
Calculated Min Value: [0.00514942 0.14155261 0.07459478]
Actual Max Value: 9
Calculated Max Value: [29.98738487 30.12378807 30.05683024]

In [12]:
from sklearn.metrics import mean_squared_error, r2_score

# Use our model to predict a value
predicted = model.predict(X)

# Score the prediction with mse and r2
mse = mean_squared_error(y, predicted)
r2 = r2_score(y, predicted)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 8.135436741821307
R-squared (R2 ): 0.02786536193079836

In [ ]:
#A "good" MSE score will be close to zero while a "good" R2 Score will be close to 1.

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [14]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
model.score(X_test, y_test)

0.0059353683435914295